// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image2":
            case "rottenBanana":return img`
. . . . . . . . . . . d d . . . 
. . . . . . . . . d d 5 . . . . 
. . . . . . . d d 5 d 5 . . . . 
. . . . 5 5 d d 5 d . . . . . . 
. . . 5 d d 5 5 5 . . . . . . . 
. 5 d f 5 5 d f 5 . . . . . . . 
. 5 5 5 d d 5 5 . . . . . . . . 
. f 5 d d 5 f . . . . . . . . . 
. 5 f f 5 f 5 . . . . . . . . . 
. 5 d f f f 5 5 . . . . . . . . 
. . d 5 5 5 d d 5 . . . . . . . 
. . . 5 d d 5 d d d 5 . . . . . 
. . . . d 5 d d 5 d 5 5 . . . . 
. . . . . 5 5 5 5 5 5 d 5 5 . . 
. . . . . . . d 5 5 5 d d d . . 
. . . . . . . . . . . d 5 5 . . 
`;
            case "t[{,ZZs!jVANjxo?mj9s":
            case "archnemesis":return img`
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
...............................................................ffff.................................
...............................................................ffff.................................
...............................................................ffff.................................
...............................................................ffff.................................
............................................................fffeeeefffff............................
............................................................fffeeeefffff............................
............................................................fffeeeefffff............................
............................................................fffeeeefffff............................
........................................................ffffeeeffff.................................
........................................................ffffeeeffff.................................
.................................................fffffffeeeefff.....................................
.................................................fffffffeeeefff.....................................
.................................................fffffffeeeefff.....................................
.................................................fffffffeeeefff.....................................
.................................................fffffffeeeeeeeffff.................................
.................................................fffffffeeeeeeeffff.................................
.................................................fffffffeeeeeeeffff.................................
.................................................fffffffeeeeeeeffff.................................
......................................fffffffffffffffffffffffff.....................................
......................................fffffffffffffffffffffffff.....................................
......................................fffffffddffffffffffffffff.....................................
......................................fffffffddffffffffffffffff.....................................
......................................fffffffddffffffffffffffff.....................................
...........................fffffffffffccdddccddcccccccee7777ffffffffffff............................
...........................fffffffffffccdddccddcccccccee7777ffffffffffff............................
.........................ffcccccddccdddddddddddccccceeeeeeeeeeecceefffff............................
.........................ffcccccddccdddddddddddccccceeeeeeeeeeecceefffff............................
.........................ffdddddddccccccddddddddddddccccdd77ddddd77fffff............................
.........................ffdddddddccccccddddddddddddccccdd77ddddd77fffff............................
.........................ffddcccffffffff777ddccccdddccddfffffffffcccc777ff..........................
.........................ffddcccffffffff777ddccccdddccddfffffffffcccc777ff..........................
.........................ffdd777ffffffff777ddddccddddd77fffffffff77ee777ff..........................
.........................ffdd777ffffffff777ddddccddddd77fffffffff77ee777ff..........................
..................fffffff77dddddffffffff777ddddddcccddccfffffffff77eecccfffffffffffff...............
..................fffffff77dddddffffffff777ddddddcccddccfffffffff77eecccfffffffffffff...............
..................fffffff77dddddffffffffdddddddddcccdd77fffffffff77eeeeefffffffffffff...............
..................fffffff77dddddffffffffdddddddddcccdd77fffffffff77eeeeefffffffffffff...............
............fffffffffffffddddddd77dddddddddccdd77cccddddcccccccddcccceeeee77eefffffffff.............
............fffffffffffffddddddd77dddddddddccdd77cccddddcccccccddcccceeeee77eefffffffff.............
.......fffff7777ccccdddddddccdddddddccddddddddddddddddddcccccccdddd77eeeeeeeeeeeccccceefffffffff....
.......fffff7777ccccdddddddccdddddddccddddddddddddddddddcccccccdddd77eeeeeeeeeeeccccceefffffffff....
.......fffffccdddddddddcccc77dddddddccdddddddddcccccddccddccdddddddccdddddeecccceeeeeeefffffffff....
.......fffffccdddddddddcccc77dddddddccdddddddddcccccddccddccdddddddccdddddeecccceeeeeeefffffffff....
.......fffffddddddddcccccccdddddccddddddddddddddddddccddccccdddcccccceeeddeeccccccceeeefffffffff....
.......fffffddddddddcccccccdddddccddddddddddddddddddccddccccdddcccccceeeddeeccccccceeeefffffffff....
...ffff77dddddddddcccccccddddfff77ccccdddddccccdddddddddccccdddccccffeeeeeeeddddccceeeeeeeeeffffff..
...ffff77dddddddddcccccccddddfff77ccccdddddccccdddddddddccccdddccccffeeeeeeeddddccceeeeeeeeeffffff..
...ffff77dddddddddcccccccddddfff77ccccdddddccccdddddddddccccdddccccffeeeeeeeddddccceeeeeeeeeffffff..
...ffffccddddd7777cccccddddddfffffccccdddddddddddddddddddddd777fffffffffcceeeeeeeeeeeddeeeeeeeffff..
...ffffccddddd7777cccccddddddfffffccccdddddddddddddddddddddd777fffffffffcceeeeeeeeeeeddeeeeeeeffff..
fff77ccddddddddddddddddddcc77fffffffcccccccdd77dddddccdddd77fffffff7777777eeeeeedddeeeeeeeeeeeff....
fff77ccddddddddddddddddddcc77fffffffcccccccdd77dddddccdddd77fffffff7777777eeeeeedddeeeeeeeeeeeff....
fff77ccddddddddddddddddcccc77cccffffff77cccddddddcccccdd77fffffff7777dddeeeeccddeeeeeeecceeeeeee....
fff77ccddddddddddddddddcccc77cccffffff77cccddddddcccccdd77fffffff7777dddeeeeccddeeeeeeecceeeeeee....
...ffffcccccccddccdddddcccc77ccc7777ffffffffffffffffffffffddddddd7777dddeeeeeeeedddeeeefffffffff....
...ffffcccccccddccdddddcccc77ccc7777ffffffffffffffffffffffddddddd7777dddeeeeeeeedddeeeefffffffff....
.......ffcccccddcc77777ddddddccccccccccc7777777cccccccddddcc777ddddddeeedddddddddddeefffffff........
.......ffcccccddcc77777ddddddccccccccccc7777777cccccccddddcc777ddddddeeedddddddddddeefffffff........
.......ffccc77ddddccccc77ddddccccccc77ccddddddddddddddccccccccccccceedddddeeeeeeeee77fffffff........
.......ffccc77ddddccccc77ddddccccccc77ccddddddddddddddccccccccccccceedddddeeeeeeeee77fffffff........
.........fffccccccddddddddddddddccccdddddddddddccdddddccccdddddddddddeeeeeccddeefffffff.............
.........fffccccccddddddddddddddccccdddddddddddccdddddccccdddddddddddeeeeeccddeefffffff.............
............ff7777ccddddddddddddddddddddddddddddddddddddeedddddddddeeeeeeeeeeefffffffff.............
............ff7777ccddddddddddddddddddddddddddddddddddddeedddddddddeeeeeeeeeeefffffffff.............
..............ffcccc777ddddccccc77dddddddddddddcccccccddeecceeeeeeeeedddddfffffffffff...............
..............ffcccc777ddddccccc77dddddddddddddcccccccddeecceeeeeeeeedddddfffffffffff...............
..............ffff77cccccccccccccc77ddddddddddddddddddddeedddddddddddffffffffffffffff...............
..............ffff77cccccccccccccc77ddddddddddddddddddddeedddddddddddffffffffffffffff...............
..................ffffffffffffffffff77cccccccccccccccccccccc777fffffffff............................
..................ffffffffffffffffff77cccccccccccccccccccccc777fffffffff............................
....................................fffffffffffffffffffffffffff77eefffffff..........................
....................................fffffffffffffffffffffffffff77eefffffff..........................
....................................fffffffffffffffffffffffffff77eefffffff..........................
....................................fffffffffffccffffffffffffffeeeeeefffff..........................
....................................fffffffffffccffffffffffffffeeeeeefffff..........................
................................ffffdd77ddddddddd77777eeeeeeeeeeeeeeeeeeeeffff......................
................................ffffdd77ddddddddd77777eeeeeeeeeeeeeeeeeeeeffff......................
................................ffffdddddddccccdddddeeeecceeeeeeeeeeeeeeeeeeff......................
................................ffffdddddddccccdddddeeeecceeeeeeeeeeeeeeeeeeff......................
...........................fffffcc77ffffdddddddddeeeeeddddeeccceeeeeeeeeffeeccfffffff...............
...........................fffffcc77ffffdddddddddeeeeeddddeeccceeeeeeeeeffeeccfffffff...............
...........................fffffcc77ffffdddddccccccceeeeeeeedddddcc77777ffeeeefffffff...............
...........................fffffcc77ffffdddddccccccceeeeeeeedddddcc77777ffeeeefffffff...............
................................ffff..fffffccddddeeeeedddddddddccccfffff..ffff......................
................................ffff..fffffccddddeeeeedddddddddccccfffff..ffff......................
...........................................ffffccffffffffffffffccccfffff............................
...........................................ffffccffffffffffffffccccfffff............................
...........................................ffff77ffffffffffffff7777fffff............................
...........................................ffff77ffffffffffffff7777fffff............................
...............................................fffffffff.......fffffffff............................
...............................................fffffffff.......fffffffff............................
...............................................fffffffff.......fffffffff............................
...............................................fffffffff.......fffffffff............................
....................................................................................................
....................................................................................................
`;
            case "image3":
            case "caca":return img`
. . . . . . . . . . . . f . . . 
. . f . . . . . . . . f . . . . 
. f . . . e e e . . . . . . . . 
. . . . . e e e . . e e e . . . 
. e e e e e e 4 2 e e d e e . . 
. e d e 4 4 4 4 2 d d d c e e . 
. e e e 2 2 2 2 c 2 d c e e . . 
. . . e 2 4 4 4 4 2 d d . . . . 
. . e e e 4 d d 4 d d e e e . . 
. e e e 2 d d 4 4 d d e e e . . 
. . . d d d 4 4 2 e e e e e . . 
. . e d e 2 2 4 2 e e . e . . . 
. . . e e 4 4 4 2 e e . . . . . 
. . . . . . e e e e . . . f . . 
. f . . . e e e e . . . f . . . 
f . . . . . . . . . . . . . . . 
`;
            case "image1":
            case "greenApple":return img`
.............................
.............................
..................f..........
.................fef.........
................fef..........
...............fef...........
...............feef..........
............ffffff...........
.........fff77777fff.........
........f7777777777f.........
........f7ff7777ff77f........
.......f77ff7777ff77fff......
.....fff77777777777777ff.....
....f7777777777777777777ff...
...f7777ff77777777ff77777ff..
..f7777777f777777f7777777f...
...f7777777fffffff777777ff...
....f777777777777777777ff....
.....f7777777777777777ff.....
......f777777777777ffff......
.......ffff7777777ff.........
...........fffffff7ff........
..........f7777777777f.......
.........f7ff7777777f7f......
..........f.f777777f.f.......
.............f7fff7f.........
..............ff..ff.........
.............................
.............................
`;
            case "image4":
            case "megaspaceship":return img`
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
..........................................................................999..................................................................................
......................................................................999bbbb99b999999.........................................................................
.....................................................................baaab9bbbb99999999999.....................................................................
.....................................................................babbbbbbbbbbb9bb999b999...................................................................
...................................................................9bbaababb9999b9bbbbb99999...................................................................
................................................................99bbbbbbbaaababbbbbbbbbabbbb9..................................................................
...............................................................9bbbbbbbbbbbbbbbbbbbbb9999999999................................................................
..............................................................bbbbbbbbbbbbbb9999999b9b99999999999..............................................................
............................................................9bbbababbbbbbbbbbbbbbb9b999999999999999............................................................
...........................................................9bbbababbbbbbbbbbbbbbbbbb99999999999999999..........................................................
...........................................................bbaaaaaabaabbbbbbbbbbbb9bb999999999999999999........................................................
..........................................................baaaaaaaaaabbbbbbbbbbbbbbbb999999999999999999999.....................................................
.........................................................baaaaaaaaaaabbbbbbb9999999b99999999999999999999bb9....................................................
........................................................9aaaaaaaaaabaabbbaabbbbbb99b99999999999999bb999bbbbb...................................................
....................................................99bbaaaaaaaaaaaaaaabbbbbbbabbbbbbbbbbbbbabbbbbbbbbbbbbab9..................................................
.........................................999.9999bbbbbbbaaeaaeeaaaaaaaaaaaabbbabbbbbbbbbbbbbbbb99bbbbbbbbebbbb9999999..........................................
......................................9999bbbbbbbbbbbbbaaaaaa9eaa97aaaeeaaaaabaabaababbaabbbaabbbeebbb7bb9bbbbb999999999.......................................
...............................9999999bbbbbbbbbbbbbbabbaaaaaaeaab9baab99aab79eababbabbb9bbbb99bbb99ebb9bbbbbbbb999999999b999...................................
............................9bbbb999bbbbbbbbbbbbbbaaabbbbaaaaaaaaaaaab9baaa999aba99bbbb11bbbb19bbbebbbbbbbb99b999bbb9999bbbb99.................................
.......................999babbbbbb9abbbbbabaabbbbbaaaabbbbbbaaaaaaaaaaaaaaaaaaabbabbbbbbbbbbbbbb999999b9bbaab99999bbbbb99bbbbbb9...............................
....................9bbaaaabbbbbbbaaaaaaaaaaaaaaabaaaaaabbbbbbbbbbbbaaaaaabbbbbbbbbbbbbbbbbbbbbbbbbbbb9bb999999bbbbbb999bbbbbbbb9..............................
..................9aaaaaaabbbbbb9aaaaaaaaaaaaaaaaabbbaaaaaabbbbbbbbbbb99999bbbbaaaaaaabbbabaaabb999991199119baabbbbbab99bb99b9bbb99....9...9...................
...............9baaaaaaaabbbbbbbbaaaaaaaaaaaeaaaaaaaaaaaaaaaaaaaabbbbbbb9999999999999999999999999999bbbbbbaaabbbbbbbbaabb9bb99bbbb9999.99999999................
.............9baaaaaaaaaabbbbbbbbaaaaaaaaaaaaaaaaaaeaaaabaaaaaaaaaaaaaaaaaaaaaaabbbbbaaababbaaaaaaabaaaaaaaaabbbbbbbbbbaaab99bbbab11999999999ab9...............
............9bbaaaaaaaaaabbbbbbbbbaaaaaaaabaaaaafaaaaaaabaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbaabbbaab99999999999baabb..............
...........9bbaaaaaaaaaaabbbbbbbbbbaaaaaaaffaaaaaaaaafaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaababbbbbbbbbbbbbbbbaaab9999991bbb99baaaa9.............
..........9bbbaaaaaaaaaaaabbbbbbbbbbbaaaaaaaaaaafafaaabaaaaaaaaaaaaaaabaaaaaaaaaaaaaaaaaaaaaaaaaaaabaababbbbbbbbbbbbbbbbaaaaa9b9999999b9bbbbbaaaab.............
.........9aabbaaaaaaaaaaaaabbbbbbbbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaababbaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbaaabbbbaaaaaaaaab999999999bbbbbbbaaaaaa.............
.........9bbaabaaaabbaaaaaaaaabbbbbbbbbbbaabbaafaaaaaaaaaaaaaaaaaaaaaabaabbbbbbbbbaaaaaaaaaababaaaaaaabbbabbaaaaaaaafabbbb999999999bbbbbbbbaaaaaaa9............
.........9bbaaaabbbaababaaaaaaaabbbbbbbbbbbbaabbaaaaaaafaaaaaaaaaaaaabbbbaaaaaaaaaaaaaaaaaaaabbaaaaaaaaaaafffaaaaab99bbb99999999bbbbbbbbbbaaaaaaaba............
.........9baaaaaaaaaaaaaaaaaaaaaaaaabbbbbabbbbbbbbbbaaaaaaab9baaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbabbbfffffaaaaaaaab99b999999999bb9bbbabbbbbbbaaaaaabba............
..........bbbaaaaabaaaaabbbbaaaaaaaaaaaabbbbbbbbbbbbbbbbbba9199b9bb19aaaaaaaffffffffffffb19bb9bb11aaaaaaaabb9999999999999bbbbbbbbbbbabbbbaaaaaabb9b............
.........9bbbbbaaaaaaaaabbbbaaaaaaaaaaaaaaaabbbbbbbbbbbbbbb9199b99919bbbbbbbbbbbbbbbbbbbb119b99b11bbbb99999999999bbbbbbbbbbbbbbbbbbbbabaaaaaabbbb99............
.........9abbbbbabaaaabbabbbaaabaaaaaaaaaaaaaaaaaaaaabbbbbb91999999199999999999999999bbb9119b91b11b9999999bbbbbbbbbbbbbbbbbbabbbbbbbbbaaaaabbaa919.............
..........9bbbbbbbbbbbabaabbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa919b1bb119bbbbbbbbbbbbbbbbbbbb119b1bb11bbbbbbbbbbbbbbbbbbbbbbbbbbbabbbbbbaaabbbbbaaab99.............
............9bb99999bbaabbaabbbaaaaaaaaabaaaaaaaaaaaaaaaaaa911919b11bbbbbbbbbbbbbbbbbbab911bb19911bbaabbbbbbbbbbbbabbbbbbbbbbbbbbbbbb9999aaaaab9...............
.............9999...99bbbbbbbbbaaaaaabbaabaaaaaaaaaaaaaaaaa911111111bbbbabbbbbbbbbabababb111111111babababaabbbbbabbabbbbbbbbbbbbbb999b9.9baab9.................
...............99.b.9bbbb9bbbbbbbbbbbbbaabbbaaaaaaaaaaaaaaa911111111bbbbbbbbbbbbbabbabbbb111111111bbabaaaaabbbbbbaababbbaaabbb9999b9999.bbb9...................
.................9bb99bbbbbb999999bbbbbbbabbbaaaaaaaaaaaaaa911111111bbbbbbbbbbbbbbbbbbbab111111111bbabbabaaaaabbbaaaafaab9999bbb.99...bbb......................
...................bbbbbbaababbb999999b9bbbbbaaaaaaaaaaaaaa111111111bbbbbbbbbbbbbbbbabbab9111111119aaaaaaaaaaaabbbbbbbbbbbaaaaab..bbbbb9.......................
......................9bbaaabbbb9.999999999999bbbbaaaaaaaab111111111bbbbbbbbbbbbbbabaaaaa911111111bffaaabb99bbb919baaaaaaaaaaaabbbb............................
.........................99bbbbb9...99..9bbbb99bbbbb9bbbbbb111111119999b9999bbbbbbbbaaaaa91111111199bbbb9bbbbaa9199aaaaaaaaaabbbb..............................
..............................99bb..99..99b9b999baaabaaaaababbbbb999999999999999999bbbbbb91119999baaaabb199ababb11baabbbbb999..................................
.................................bbb99..9bbbb...baaaaaaaaaaaaaaaaaab1999911999999bbaaaaaaaaaaaaaaaaaaa99119aaaab999bbbbbbbbbbb.................................
...................................bbbbb.99999.9baaaaaaaaaaaaaababb91119111191111b9aaaaaaaaaaaaaaaaaabbb99bb99999bbb...........................................
........................................bbbbb..99baaabbbbbbbabbbbbb91199911199911baaaaaaaaaaaabbbaaaaaabbbbbbbbbb..............................................
............................................bbbbb9bbbaaaaaaaabbbbbbbbbbbb999bbb99bbaaaaaaaaaaabbbbbbbbb.bbbbb..................................................
......................................................99bbaaabbbbaaaaabbaaaaaaebbbbbbbbbbbbbbbbbbbbbbbbbbbb....................................................
............................................................9baaaaaaaaabbbbbbabbbbbbbbbbbaaaaabb9bbbb..........................................................
.............................................................999baaaaaaaaaaaaaaaaaaaaaaaaaaab99................................................................
.................................................................199bbaaaaaaaaaaaaaaaaabb991...................................................................
......................................................................111999..........119......................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
...............................................................................................................................................................
`;
            case "image5":
            case "smalspaceship":return img`
. . . . . . . . . . . . . . . . . . 
. . . . . . 1 1 1 1 1 1 1 . . . . . 
. . . . . 1 1 1 1 1 1 1 1 1 . . . . 
. . . . . 1 1 1 1 1 1 1 1 1 . . . . 
. . . . 1 1 1 1 1 1 1 1 1 1 . . . . 
. . . . 1 1 1 1 1 1 1 1 1 1 . . . . 
. . . . 1 1 1 1 1 1 1 1 1 1 . . . . 
. b 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 . 
. b 9 9 5 9 9 9 9 9 9 9 9 9 5 b b . 
. b b 9 9 9 9 9 9 5 9 9 9 9 b b . . 
. . b b b b 9 9 9 9 9 9 9 b b . . . 
. . . . . b b b b b b b b b . . . . 
. . . . . . . . . . . . . . . . . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
