// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "myImage":return img`
.............................
.............................
..................f..........
.................fef.........
................fef..........
...............fef...........
...............feef..........
............ffffff...........
.........fff77777fff.........
........f7777777777f.........
........f7ff7777ff77f........
.......f77ff7777ff77fff......
.....fff77777777777777ff.....
....f7777777777777777777ff...
...f7777ff77777777ff77777ff..
..f7777777f777777f7777777f...
...f7777777fffffff777777ff...
....f777777777777777777ff....
.....f7777777777777777ff.....
......f777777777777ffff......
.......ffff7777777ff.........
...........fffffff7ff........
..........f7777777777f.......
.........f7ff7777777f7f......
..........f.f777777f.f.......
.............f7fff7f.........
..............ff..ff.........
.............................
.............................
`;
            case "t[{,ZZs!jVANjxo?mj9s":
            case "archnemesis":return img`
..................................................
..................................................
..................................................
..................................................
..............................ff..................
..............................ff..................
.............................feeff................
.............................feeff................
...........................ffeff..................
........................fffeef....................
........................fffeef....................
........................fffeeeff..................
........................fffeeeff..................
...................fffffffffff....................
...................fffdfffffff....................
..............fffffcdcdccce77fffff................
.............fccdcdddddcceeeeeceff................
.............fdddcccdddddccd7dd7ff................
.............fdcffff7dccdcdffffcc7f...............
.............fd7ffff7ddcdd7ffff7e7f...............
..........fff7ddffff7dddcdcffff7ecffffff..........
..........fff7ddffffddddcd7ffff7eeffffff..........
.......ffffffddd7ddddcd7cddcccdccee7effff.........
.....ff77ccdddcdddcddddddddcccdd7eeeeecceffff.....
.....ffcddddcc7dddcddddccdcdcdddcddecceeeffff.....
.....ffddddcccddcddddddddcdccdcccedeccceeffff.....
...ff7ddddcccddf7ccddccddddccdccfeeeddceeeefff....
...ffcdd77ccdddffccdddddddddd7ffffceeeeedeeeff....
..f7cddddddddc7fffcccd7ddcdd7fff777eeedeeeeef.....
..f7cdddddddcc7cfff7cdddccd7fff77deecdeeeceee.....
...ffcccdcddcc7c77ffffffffffddd77deeeedeeffff.....
.....fccdc77dddccccc777cccddc7dddedddddefff.......
.....fc7ddcc7ddccc7cddddddcccccceddeeee7fff.......
......fcccddddddccdddddcddccdddddeecdefff.........
.......f77cddddddddddddddddeddddeeeeeffff.........
........fcc7ddcc7ddddddcccdeceeeeddfffff..........
........ff7cccccc7dddddddddedddddfffffff..........
..........ffffffff7cccccccccc7ffff................
..................ffffffffffff7efff...............
..................fffffcffffffeeeff...............
................ffd7dddd77eeeeeeeeeff.............
................ffdddccddeeceeeeeeeef.............
..............ffc7ffddddeeddeceeeefecfff..........
..............ffc7ffddccceeeeddc77feefff..........
................ff.ffcddeeddddccff.ff.............
.....................ffcffffffccff................
.....................ff7ffffff77ff................
.......................ffff...ffff................
.......................ffff...ffff................
..................................................
`;
            case "image2":
            case "rottenBanana":return img`
. . . . . . . . . . . d d . . . 
. . . . . . . . . d d 5 . . . . 
. . . . . . . d d 5 d 5 . . . . 
. . . . 5 5 d d 5 d . . . . . . 
. . . 5 d d 5 5 5 . . . . . . . 
. 5 d f 5 5 d f 5 . . . . . . . 
. 5 5 5 d d 5 5 . . . . . . . . 
. f 5 d d 5 f . . . . . . . . . 
. 5 f f 5 f 5 . . . . . . . . . 
. 5 d f f f 5 5 . . . . . . . . 
. . d 5 5 5 d d 5 . . . . . . . 
. . . 5 d d 5 d d d 5 . . . . . 
. . . . d 5 d d 5 d 5 5 . . . . 
. . . . . 5 5 5 5 5 5 d 5 5 . . 
. . . . . . . d 5 5 5 d d d . . 
. . . . . . . . . . . d 5 5 . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
