// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "myImage":return img`
.............................
.............................
..................f..........
.................fef.........
................fef..........
...............fef...........
...............feef..........
............ffffff...........
.........fff77777fff.........
........f7777777777f.........
........f7ff7777ff77f........
.......f77ff7777ff77fff......
.....fff77777777777777ff.....
....f7777777777777777777ff...
...f7777ff77777777ff77777ff..
..f7777777f777777f7777777f...
...f7777777fffffff777777ff...
....f777777777777777777ff....
.....f7777777777777777ff.....
......f777777777777ffff......
.......ffff7777777ff.........
...........fffffff7ff........
..........f7777777777f.......
.........f7ff7777777f7f......
..........f.f777777f.f.......
.............f7fff7f.........
..............ff..ff.........
.............................
.............................
`;
            case "image2":
            case "rottenBanana":return img`
. . . . . . . . . . . d d . . . 
. . . . . . . . . d d 5 . . . . 
. . . . . . . d d 5 d 5 . . . . 
. . . . 5 5 d d 5 d . . . . . . 
. . . 5 d d 5 5 5 . . . . . . . 
. 5 d f 5 5 d f 5 . . . . . . . 
. 5 5 5 d d 5 5 . . . . . . . . 
. f 5 d d 5 f . . . . . . . . . 
. 5 f f 5 f 5 . . . . . . . . . 
. 5 d f f f 5 5 . . . . . . . . 
. . d 5 5 5 d d 5 . . . . . . . 
. . . 5 d d 5 d d d 5 . . . . . 
. . . . d 5 d d 5 d 5 5 . . . . 
. . . . . 5 5 5 5 5 5 d 5 5 . . 
. . . . . . . d 5 5 5 d d d . . 
. . . . . . . . . . . d 5 5 . . 
`;
            case "t[{,ZZs!jVANjxo?mj9s":
            case "archnemesis":return img`
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
...............................................................ffff.................................
...............................................................ffff.................................
...............................................................ffff.................................
...............................................................ffff.................................
............................................................fffeeeefffff............................
............................................................fffeeeefffff............................
............................................................fffeeeefffff............................
............................................................fffeeeefffff............................
........................................................ffffeeeffff.................................
........................................................ffffeeeffff.................................
.................................................fffffffeeeefff.....................................
.................................................fffffffeeeefff.....................................
.................................................fffffffeeeefff.....................................
.................................................fffffffeeeefff.....................................
.................................................fffffffeeeeeeeffff.................................
.................................................fffffffeeeeeeeffff.................................
.................................................fffffffeeeeeeeffff.................................
.................................................fffffffeeeeeeeffff.................................
......................................fffffffffffffffffffffffff.....................................
......................................fffffffffffffffffffffffff.....................................
......................................fffffffddffffffffffffffff.....................................
......................................fffffffddffffffffffffffff.....................................
......................................fffffffddffffffffffffffff.....................................
...........................fffffffffffccdddccddcccccccee7777ffffffffffff............................
...........................fffffffffffccdddccddcccccccee7777ffffffffffff............................
.........................ffcccccddccdddddddddddccccceeeeeeeeeeecceefffff............................
.........................ffcccccddccdddddddddddccccceeeeeeeeeeecceefffff............................
.........................ffdddddddccccccddddddddddddccccdd77ddddd77fffff............................
.........................ffdddddddccccccddddddddddddccccdd77ddddd77fffff............................
.........................ffddcccffffffff777ddccccdddccddfffffffffcccc777ff..........................
.........................ffddcccffffffff777ddccccdddccddfffffffffcccc777ff..........................
.........................ffdd777ffffffff777ddddccddddd77fffffffff77ee777ff..........................
.........................ffdd777ffffffff777ddddccddddd77fffffffff77ee777ff..........................
..................fffffff77dddddffffffff777ddddddcccddccfffffffff77eecccfffffffffffff...............
..................fffffff77dddddffffffff777ddddddcccddccfffffffff77eecccfffffffffffff...............
..................fffffff77dddddffffffffdddddddddcccdd77fffffffff77eeeeefffffffffffff...............
..................fffffff77dddddffffffffdddddddddcccdd77fffffffff77eeeeefffffffffffff...............
............fffffffffffffddddddd77dddddddddccdd77cccddddcccccccddcccceeeee77eefffffffff.............
............fffffffffffffddddddd77dddddddddccdd77cccddddcccccccddcccceeeee77eefffffffff.............
.......fffff7777ccccdddddddccdddddddccddddddddddddddddddcccccccdddd77eeeeeeeeeeeccccceefffffffff....
.......fffff7777ccccdddddddccdddddddccddddddddddddddddddcccccccdddd77eeeeeeeeeeeccccceefffffffff....
.......fffffccdddddddddcccc77dddddddccdddddddddcccccddccddccdddddddccdddddeecccceeeeeeefffffffff....
.......fffffccdddddddddcccc77dddddddccdddddddddcccccddccddccdddddddccdddddeecccceeeeeeefffffffff....
.......fffffddddddddcccccccdddddccddddddddddddddddddccddccccdddcccccceeeddeeccccccceeeefffffffff....
.......fffffddddddddcccccccdddddccddddddddddddddddddccddccccdddcccccceeeddeeccccccceeeefffffffff....
...ffff77dddddddddcccccccddddfff77ccccdddddccccdddddddddccccdddccccffeeeeeeeddddccceeeeeeeeeffffff..
...ffff77dddddddddcccccccddddfff77ccccdddddccccdddddddddccccdddccccffeeeeeeeddddccceeeeeeeeeffffff..
...ffff77dddddddddcccccccddddfff77ccccdddddccccdddddddddccccdddccccffeeeeeeeddddccceeeeeeeeeffffff..
...ffffccddddd7777cccccddddddfffffccccdddddddddddddddddddddd777fffffffffcceeeeeeeeeeeddeeeeeeeffff..
...ffffccddddd7777cccccddddddfffffccccdddddddddddddddddddddd777fffffffffcceeeeeeeeeeeddeeeeeeeffff..
fff77ccddddddddddddddddddcc77fffffffcccccccdd77dddddccdddd77fffffff7777777eeeeeedddeeeeeeeeeeeff....
fff77ccddddddddddddddddddcc77fffffffcccccccdd77dddddccdddd77fffffff7777777eeeeeedddeeeeeeeeeeeff....
fff77ccddddddddddddddddcccc77cccffffff77cccddddddcccccdd77fffffff7777dddeeeeccddeeeeeeecceeeeeee....
fff77ccddddddddddddddddcccc77cccffffff77cccddddddcccccdd77fffffff7777dddeeeeccddeeeeeeecceeeeeee....
...ffffcccccccddccdddddcccc77ccc7777ffffffffffffffffffffffddddddd7777dddeeeeeeeedddeeeefffffffff....
...ffffcccccccddccdddddcccc77ccc7777ffffffffffffffffffffffddddddd7777dddeeeeeeeedddeeeefffffffff....
.......ffcccccddcc77777ddddddccccccccccc7777777cccccccddddcc777ddddddeeedddddddddddeefffffff........
.......ffcccccddcc77777ddddddccccccccccc7777777cccccccddddcc777ddddddeeedddddddddddeefffffff........
.......ffccc77ddddccccc77ddddccccccc77ccddddddddddddddccccccccccccceedddddeeeeeeeee77fffffff........
.......ffccc77ddddccccc77ddddccccccc77ccddddddddddddddccccccccccccceedddddeeeeeeeee77fffffff........
.........fffccccccddddddddddddddccccdddddddddddccdddddccccdddddddddddeeeeeccddeefffffff.............
.........fffccccccddddddddddddddccccdddddddddddccdddddccccdddddddddddeeeeeccddeefffffff.............
............ff7777ccddddddddddddddddddddddddddddddddddddeedddddddddeeeeeeeeeeefffffffff.............
............ff7777ccddddddddddddddddddddddddddddddddddddeedddddddddeeeeeeeeeeefffffffff.............
..............ffcccc777ddddccccc77dddddddddddddcccccccddeecceeeeeeeeedddddfffffffffff...............
..............ffcccc777ddddccccc77dddddddddddddcccccccddeecceeeeeeeeedddddfffffffffff...............
..............ffff77cccccccccccccc77ddddddddddddddddddddeedddddddddddffffffffffffffff...............
..............ffff77cccccccccccccc77ddddddddddddddddddddeedddddddddddffffffffffffffff...............
..................ffffffffffffffffff77cccccccccccccccccccccc777fffffffff............................
..................ffffffffffffffffff77cccccccccccccccccccccc777fffffffff............................
....................................fffffffffffffffffffffffffff77eefffffff..........................
....................................fffffffffffffffffffffffffff77eefffffff..........................
....................................fffffffffffffffffffffffffff77eefffffff..........................
....................................fffffffffffccffffffffffffffeeeeeefffff..........................
....................................fffffffffffccffffffffffffffeeeeeefffff..........................
................................ffffdd77ddddddddd77777eeeeeeeeeeeeeeeeeeeeffff......................
................................ffffdd77ddddddddd77777eeeeeeeeeeeeeeeeeeeeffff......................
................................ffffdddddddccccdddddeeeecceeeeeeeeeeeeeeeeeeff......................
................................ffffdddddddccccdddddeeeecceeeeeeeeeeeeeeeeeeff......................
...........................fffffcc77ffffdddddddddeeeeeddddeeccceeeeeeeeeffeeccfffffff...............
...........................fffffcc77ffffdddddddddeeeeeddddeeccceeeeeeeeeffeeccfffffff...............
...........................fffffcc77ffffdddddccccccceeeeeeeedddddcc77777ffeeeefffffff...............
...........................fffffcc77ffffdddddccccccceeeeeeeedddddcc77777ffeeeefffffff...............
................................ffff..fffffccddddeeeeedddddddddccccfffff..ffff......................
................................ffff..fffffccddddeeeeedddddddddccccfffff..ffff......................
...........................................ffffccffffffffffffffccccfffff............................
...........................................ffffccffffffffffffffccccfffff............................
...........................................ffff77ffffffffffffff7777fffff............................
...........................................ffff77ffffffffffffff7777fffff............................
...............................................fffffffff.......fffffffff............................
...............................................fffffffff.......fffffffff............................
...............................................fffffffff.......fffffffff............................
...............................................fffffffff.......fffffffff............................
....................................................................................................
....................................................................................................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
